### ISSUE TITLE
Are ‘visual_feature.h5’ and ‘visual_feature_vec.h5’ the same file? 

### ISSUE THREAD

**Issue by laohuijiadezhu** [L-YeZhu/Learning-Audio-Visual-Correlations#1]
If not, how can I get the ‘visual_feature_vec.h5’?
![image](https://user-images.githubusercontent.com/59173157/114293996-8c6f2700-9acd-11eb-85db-515ecda1010e.png)

![image](https://user-images.githubusercontent.com/59173157/114293968-5d58b580-9acd-11eb-93e4-7fbd8f56b219.png)

**Comment by L-YeZhu** [comment]
Hi,

visial_feature.h5 and visual_feature_vec.h5 are different files. Both are available for download from the original AVE dataset repo. The visual_feature_vec.h5 is under their "Cross-modality localization" section, which are obtained via global average pooling.
