### ISSUE TITLE
broadcast problem！

### ISSUE THREAD

**Issue by lircsszz** [L-YeZhu/Learning-Audio-Visual-Correlations#2]
Hi，I met a problem when tring run msvae.py
raceback (most recent call last):
  File "msvae.py", line 65, in <module>
    x_video_val[10 * i + j, :] = video_features[id, j, :]
ValueError: could not broadcast input array from shape (7,7,512) into shape (512)
my pytorch version is 1.4.0

**Comment by lircsszz** [comment]
> Hi，I met a problem when tring run msvae.py raceback (most recent call last): File "msvae.py", line 65, in x_video_val[10 * i + j, :] = video_features[id, j, :] ValueError: could not broadcast input array from shape (7,7,512) into shape (512) my pytorch version is 1.4.0

I found out the video_features from visual_feature.h5 suppose to be (4143, 10, 512), but actually it is (4143, 10, 7, 7, 512)
so how to fix this problem?
ps: the  visual_feature.h5 are download from https://github.com/YapengTian/AVE-ECCV18

**Comment by L-YeZhu** [comment]
Hi, you could try to download the features after the avg pooling processing (available under the cross-modality localization section in https://github.com/YapengTian/AVE-ECCV18 ).

**Comment by lircsszz** [comment]
> Hi, you could try to download the features after the avg pooling processing (available under the cross-modality localization section in https://github.com/YapengTian/AVE-ECCV18 ).

Great！
